name: Pull & Deploy

on:
  push:
    branches: ["dev", "main", "master"]

jobs:
  deploy-dev:
    # if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Deploy NodeJS App
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          script: |
            cd /mnt/storytime
            git pull origin dev
            npm install
            pm2 restart apis-storytime 

  deploy-master:
    # if: github.ref == 'refs/heads/master'
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: echo '${{secrets.FIREBASE_JSON}}' > firebase.json
    - run: git checkout main
    - run: git pull
    - run: npm install
    - run: echo '${{secrets.PROD_ENV}}' > .env
    - run: pm2 restart apis-story-time
